# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_number', models.IntegerField()),
                ('minor_number', models.IntegerField()),
                ('info', models.CharField(max_length=300)),
            ],
        ),
    ]
